[project]
name = "spotter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "djangorestframework>=3.16.1",
    "geopy>=2.4.1",
    "python-decouple>=3.8",
    "uvicorn>=0.40.0",
]
